### ISSUE TITLE
Compatibilty with latest version of jQuery

### ISSUE THREAD

**Issue by sharpenedpixels** [campuspress/divi-accessibility#24]
Hi,

Is it likely that this plugin will ever be compatible with the latest jQuery and jQuery migrate versions?

I’m trying to create a fully secure WordPress installation that uses all the latest technologies, this plugin throws up some console errors when the latest version of jQuery is used. See below:

```
Uncaught ReferenceError: jQuery is not defined
    at (index):17
(anonymous) @ (index):17
(index):18 Uncaught ReferenceError: jQuery is not defined
    at (index):18
(anonymous) @ (index):18
(index):18 Uncaught ReferenceError: jQuery is not defined
    at (index):18
(anonymous) @ (index):18
(index):18 Uncaught ReferenceError: jQuery is not defined
    at (index):18
(anonymous) @ (index):18
(index):19 Uncaught ReferenceError: jQuery is not defined
    at (index):19
(anonymous) @ (index):19
(index):19 Uncaught ReferenceError: jQuery is not defined
    at (index):19
```

It would be great if it were compatible with all versions and future releases.

Please let me know if this is possible or would cause problems, I may have to find an alternative method if it isn’t achievable.

Many thanks,
Kevin

**Comment by vladislavbailovic** [comment]
Unfortunately, I was unable to reproduce this behavior with Divi + Divi Accessibility plugin, and the latest jQuery (v3.4.1) loaded from several CDNs, minified or not. I suspect this issue isn't caused by jQuery version itself, but rather how the default jQuery shipping with WP core has been replaced, or the way it's being loaded. Could you please provide some more insight into your setup - most importantly, how the core version of jQuery is being replaced - and/or some steps on how exactly to reproduce the issue you faced?

As a side note, replacing the jQuery bundled with WP core with random hardcoded versions is a questionable practice, and one that comes with great potential of facing various issues with plugins that try to make use of it (and, of course, an additional responsibility of keeping your custom jQuery at least somewhat up to date - there are plenty of sites still running ancient jQuery versions today because of their theme choice).

**Comment by sharpenedpixels** [comment]
Hi Vlad,

I'm replacing the jquery files within a child theme using the functions.php file. I'm using a CDN to load the jquery files from also.

Please see below for the code used to replace the core files:

function replace_core_jquery_version() {
    wp_deregister_script( 'jquery-core' );
    wp_register_script( 'jquery-core', "https://code.jquery.com/jquery-3.4.1.min.js", array(), '3.4.1' );
    wp_deregister_script( 'jquery-migrate' );
    wp_register_script( 'jquery-migrate', "https://code.jquery.com/jquery-migrate-3.1.0.min.js", array(), '3.1.0' );
	wp_deregister_script( 'jquery-ui-core' );
    wp_register_script( 'jquery-ui-core', "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js", array(), '1.12.1' );
}
add_action( 'wp_enqueue_scripts', 'replace_core_jquery_version' );

------------------------------------------------

I have just tried this again, as it was a long time ago when I was seeing the issue and reported it. I wanted to see if it had been fixed without me realising. I've just added the above code to the functions.php file again and it is giving me errors in the console again in Chrome (not sure if any others are, as this is the primary browser I use). Also, when the page is first loaded, the skip to content link is not displayed on first press of the tab button. And, if I deactivate the plugin the console errors are gone. If I remove the code to replace the jquery files, then the plugin works as it should. However, I really would like to be able to run the latest stable versions of jQuery as all the other plugins I use and the theme seem to work fine with the latest.

If you could get back to me as soon as you've had chance to try and recreate the issue, I would be extremely grateful.

Many thanks,
Kevin

**Comment by sharpenedpixels** [comment]
> Unfortunately, I was unable to reproduce this behavior with Divi + Divi Accessibility plugin, and the latest jQuery (v3.4.1) loaded from several CDNs, minified or not.

Just thinking about it, if you could point me in the direction of how you replaced the jquery files without it causing issues, that would be a great help.

**Comment by vladislavbailovic** [comment]
That's quite odd, I have used pretty much exactly the same code, but it seemed to work well. Do you perhaps have a public URL available? It doesn't necessarily have to have the plugin activated, I just want to double-check the enqueueing order and any additional script tag attributes (if any), to try and figure out what I'm missing.

Meanwhile, you may want to check out the new stuff in [the new branch](/campuspress/divi-accessibility/tree/new/refactor-inline-resources), we have changed the plugin internals _a lot_, most notably loading the frontend resources. Also, if this still produces the same result on your end, would you please try adding this to your `functions.php`:

```(php)
add_filter( 'divi_accessibility_enqueue', '__return_true' );
```
☝ that will force the plugin to try and enqueue the resources rather than printing them inline, which might help with the issue.

**Comment by sharpenedpixels** [comment]
Hi Vlad,

I've tried adding:

`add_filter( 'divi_accessibility_enqueue', '__return_true' );`

Unfortunately, no change.

Here is a live site that currently has the plugin active. This site is also replacing the jQuery using the method I previously posted. And, it also has the code you provided in the 'functions.php' file.

See here: https://test.sharpenedpixels.co.uk

I look forward to your response.

Many thanks,
Kevin

**Comment by vladislavbailovic** [comment]
Thank you very much for sharing the link, this helped a lot! The issue is actually not really with jQuery being replaced with the latest one - rather, the issue is that it is being deferred (`<script ... defer></script>`). Adding this attribute means that:

> [...] the script is meant to be executed after the document has been parsed [...]
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

... which is, unfortunately, way too late for stuff injected directly into the document body (which is the way that the code in current master works).

The good news is that we now zeroed in on the problem, and not deferring jQuery should clear the issue with v1.x plugin (i.e. the code in current master branch). As for how to get there in practical terms, I am not sure which method is being used to defer jQuery loading. If you are using a plugin to achieve this, there is usually an area where you can influence individual scripts and disable deferring. If you are doing it via some custom code, you can try and filter out jQuery from the script tags you're adding the `defer` attribute to.

Also on this note, the filter I mentioned in my previous response (`divi_accessibility_enqueue`) only works with the new code (v2.x of the plugin - i.e. the code from this branch: https://github.com/campuspress/divi-accessibility/tree/new/refactor-inline-resources ) - unfortunately, it won't affect the code in v1.x whatsoever. I'm sorry for not being very clear about it earlier. Anyway, I have tested the new branch code with deferred jQuery and it exhibited the similar issue out of the box - _however_ adding this behavior modification filter cleared the issue for me and seemed to work well, so perhaps that's something you can try as well.

**Comment by sharpenedpixels** [comment]
Thanks very much for the insight.

I have now tested with excluding those replaced jquery files from deferring and that fixed the problem for v1.x

And, I have installed the branch version you mentioned and used the code to enqueue divi accessibility and leaving the jquery deferred and that also now works.

Thank you very much for all your help.

Kind regards,
Kevin
