### ISSUE TITLE
Why was this plugin pulled from the directory?

### ISSUE THREAD

**Issue by swinterroth** [campuspress/divi-accessibility#29]
Hello! I'm a user of this plugin and I would like to inquire why this plugin is no longer on the WP plugin repo?  Thanks

**Comment by burtrw** [comment]
Hi there,  there was a problem reported to WordPress.org about the name of the plugin. No worries though, it will continue to be maintained here. We will work to help support update notifications just like you are used to from the Github version as well soon, so that you can keep the plugin updated just like any other. In the meantime, we encourage everyone to reach out to Elegant Thems (the developers of Divi) to incorporate accessibility best practices into Divi itself so that a plugin would not be needed.
