### ISSUE TITLE
Form Field Titles Disappear

### ISSUE THREAD

**Issue by spidercreations** [campuspress/divi-accessibility#42]
Working on accessibility and found your plugin. I have the following CSS added to the site to display the Titles of form fields in support of ADA compliance.
`/* show labels above ALL form fields for ADA compliance */
.et_pb_contact_form_label {
    display: block;
}`
That works as expected, but as soon as I activate your plugin, those titles disappear. Any suggestions here?

**Comment by alexstine** [comment]
Hello @spidercreations 

This is likely because most people don't want to see the labels so our plugin automatically adds a class that makes them only visible to screen readers. I could probably add an option in a future release. I would for now keep the label option unchecked.

Hope it helps and I will keep this updated.

Thanks.

**Comment by spidercreations** [comment]
Gotcha. That makes sense. So what I did was add back the field description text, and the testing tools do not have a problem with the field titles not displayed since they see they are viewable by the screen readers.
